<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.8.2.1 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php,v 1.23.2.10.2.1 2006/08/01 14:01:37 lem9 Exp $
 * Date: Wed, 09 Aug 2006 15:57:11 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (config:root) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['socket']    = '/var/lib/mysql/mysql.sock';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'rouTer99';

/* End of servers configuration */

?>
